#!/usr/bin/sh

sudo apt-get update
sudo apt-get install -y git vim zsh tmux tig httpie tree

##zsh
chsh -s $(which zsh)
wget --no-check-certificate https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh

##dotfiles
git clone https://github.com/kimlai/dotfiles.git && cd dotfiles

for configFile in $(ls -I bootstrap.bash -I rcrc -I README.md)
do
    ln -snf $PWD/$configFile $HOME/.$configFile
done

##vim
git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
vim - +PluginInstall +qall
